version: "3.3"

services:

  rmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672

  worker:
    build: ./worker
    depends_on:
      - rmq
